### PR TITLE
fixup! Travis improve

### PR DESCRIPTION
**Pull request by greg0ire**

### CODE REVIEW

**Comment by greg0ire** [comment]
Found the solution! Please `rebase --autosquash` this

**Comment by soullivaneuh** [comment]
Easy as this? Well.

How did you find this solution?

**Comment by greg0ire** [comment]
I knew the file was there, so the only possibility was that the autoloader was failing. I usually autoload things with this `bootstrap` configuration key (the thing with phpunit finding the autoload file itself must be quite recent), so I checked for it, only to find there was no `bootstrap` entry… I then looked into phpunit and discovered [this](https://github.com/sebastianbergmann/phpunit/blob/49c2007b90b8a619e2057785e8fbc331b7b760ff/phpunit#L16) at the very beginning. A bit strange to have phpunit coupled to composer, but quite handy, and Composer is here to stay, so…

**Comment by soullivaneuh** [comment]
I see. GG! :+1:

**Pull request merged**
